repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
    args:
      - --allow-multiple-documents
  - id: flake8
    args:
      - --max-line-length=120
      - --exclude=*/migrations/*,docs/*,cex/test_settings.py
      - --ignore=E126,E203,E501,W503
  - id: requirements-txt-fixer
    args:
      - requirements/requirements.txt
      - requirements/requirements-dev.txt
      - requirements/requirements-test.txt
- repo: git://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args:
        - --line-length=120
        - --safe
        - --exclude='cex/test_settings.py'
